# frozen_string_literal: true
source "https://rubygems.org"

gem 'rspec',     '3.6.0.beta2'
gem 'coderay',   '1.1.0'
gem 'rack-test', '0.6.3'
gem 'sinatra',   '1.4.8'
gem 'sequel',    '4.42.1'
gem 'sqlite3',   '1.3.13'
