# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rspec',       '3.6.0'
gem 'coderay',     '1.1.1'
gem 'taxjar-ruby', '1.7.0'
gem 'dotenv',      '2.2.1'
