# frozen_string_literal: true
source "https://rubygems.org"

gem 'rspec',     '3.6.0'
gem 'coderay',   '1.1.1'
gem 'rack-test', '0.6.3'
gem 'sinatra',   '2.0.0'
gem 'sequel',    '4.46.0'
gem 'sqlite3',   '1.3.13'

gem 'pry', '0.10.4'
